version: "3"

services: 
  vue-ui:
    container_name: vue-ui
    restart: always
    build: ./frontend
    ports:
      - "8080:8080"
    volumes: 
      - ./frontend:/usr/src/app/ui
    links:
      - node-server
    environment: 
      - CHOKIDAR_USEPOLLING=true
    networks:
      default:
        aliases:
          - vue-ui
  node-server:
    container_name: node-api
    restart: always
    build: ./backend
    ports:
      - "3000:3000"
    volumes: 
      - ./backend:/usr/src/app
    links:
      - mongodb
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      default:
        aliases:
          - node-server
  mongodb:
    container_name: mongodb-server
    image: mongo
    logging:
      driver: "none"
    ports: 
      - "27018:27017"
    